# A generic, single database configuration.

[alembic]
# path to migration environment
script_location = alembic

# sys.path prepends - so alembic can find the app package
prepend_sys_path = .

# the database URL is set programmatically in env.py
# using the app's settings, so we leave this empty here.
# sqlalchemy.url =


# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
